#!/bin/bash
# setup.sh — one-time setup for iphone-android-sync
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLIST_LABEL="com.user.photos-sync"
PLIST_DEST="$HOME/Library/LaunchAgents/${PLIST_LABEL}.plist"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

ok()   { echo -e "${GREEN}  ✓${NC} $1"; }
warn() { echo -e "${YELLOW}  !${NC} $1"; }
err()  { echo -e "${RED}  ✗${NC} $1"; }

echo ""
echo "╔══════════════════════════════════════╗"
echo "║     iphone-android-sync setup        ║"
echo "╚══════════════════════════════════════╝"
echo ""

# ===== 1. CHECK PREREQUISITES =====
echo "── Checking prerequisites ──"

check_cmd() {
  if command -v "$1" >/dev/null 2>&1; then
    ok "$1 found"
    return 0
  else
    return 1
  fi
}

need_brew=()
check_cmd ffmpeg    || need_brew+=(ffmpeg)
check_cmd exiftool  || need_brew+=(exiftool)
check_cmd python3   || { err "python3 not found — install Xcode Command Line Tools: xcode-select --install"; exit 1; }

if [ ${#need_brew[@]} -gt 0 ]; then
  warn "Missing: ${need_brew[*]}"
  read -p "  Install via Homebrew now? [Y/n] " yn
  if [[ ! "$yn" =~ ^[Nn]$ ]]; then
    if ! command -v brew >/dev/null 2>&1; then
      err "Homebrew not found. Install it first: https://brew.sh"
      exit 1
    fi
    brew install "${need_brew[@]}"
  fi
fi

# ===== 2. INSTALL PYMOBILEDEVICE3 =====
echo ""
echo "── Setting up pymobiledevice3 ──"
PMD3_VENV="$HOME/.local/pmd3-venv"
if [ -f "$PMD3_VENV/bin/pymobiledevice3" ]; then
  ok "pymobiledevice3 already installed"
else
  echo "  Installing pymobiledevice3 (this may take a minute)..."
  python3 -m venv "$PMD3_VENV"
  "$PMD3_VENV/bin/pip" install --quiet pymobiledevice3
  ok "pymobiledevice3 installed"
fi

# ===== 3. CONFIG =====
echo ""
echo "── Configuration ──"

# Load existing config as defaults if present
[ -f "$SCRIPT_DIR/config.sh" ] && source "$SCRIPT_DIR/config.sh"

prompt() {
  local label="$1" default="$2" var="$3"
  read -p "  $label${default:+ [$default]}: " val
  val="${val:-$default}"
  printf -v "$var" '%s' "$val"
}

prompt "Export directory" "${EXPORT_DIR:-$HOME/Pictures/photos-export}" EXPORT_DIR
mkdir -p "$EXPORT_DIR"

echo ""
echo "  Telegram notifications (press Enter to skip / keep existing)"
prompt "  Bot token" "$TELEGRAM_BOT_TOKEN" TELEGRAM_BOT_TOKEN
prompt "  Chat ID"   "$TELEGRAM_CHAT_ID"   TELEGRAM_CHAT_ID

echo ""
echo "  Android (Termux SSH)"
prompt "  SSH username" "${ANDROID_SSH_USER:-u0_a32}" ANDROID_SSH_USER
prompt "  SSH port"     "${ANDROID_SSH_PORT:-8022}"   ANDROID_SSH_PORT
prompt "  Tailscale IP (100.x.x.x)" "$ANDROID_TAILSCALE_IP" ANDROID_TAILSCALE_IP

echo ""
echo "  Home WiFi (auto-starts Tailscale when away)"
current_ssid=$(networksetup -getairportnetwork en0 2>/dev/null | sed 's/Current Wi-Fi Network: //')
prompt "  Home WiFi SSID" "${HOME_WIFI_SSID:-$current_ssid}" HOME_WIFI_SSID

# Write config.sh
cat > "$SCRIPT_DIR/config.sh" <<EOF
# iphone-android-sync configuration — generated by setup.sh

EXPORT_DIR="$EXPORT_DIR"
PMD3_VENV="$HOME/.local/pmd3-venv"

TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID="$TELEGRAM_CHAT_ID"

ANDROID_SSH_USER="$ANDROID_SSH_USER"
ANDROID_SSH_PORT="$ANDROID_SSH_PORT"
ANDROID_TAILSCALE_IP="$ANDROID_TAILSCALE_IP"

HOME_WIFI_SSID="$HOME_WIFI_SSID"

ANDROID_MIN_FREE_KB=\$((15 * 1024 * 1024))
EOF
ok "config.sh written"

# ===== 4. SSH KEY FOR ANDROID =====
echo ""
echo "── Android SSH key ──"
SSH_KEY="$HOME/.ssh/id_ed25519_android_sync"
if [ -f "$SSH_KEY" ]; then
  ok "SSH key already exists at $SSH_KEY"
else
  read -p "  Generate a dedicated SSH key for Android? [Y/n] " yn
  if [[ ! "$yn" =~ ^[Nn]$ ]]; then
    ssh-keygen -t ed25519 -f "$SSH_KEY" -N "" -C "iphone-android-sync@$(hostname -s)"
    ok "SSH key generated"
    echo ""
    echo "  ┌─ Copy this public key to your Android device ─────────────────┐"
    cat "$SSH_KEY.pub"
    echo "  └───────────────────────────────────────────────────────────────┘"
    echo ""
    echo "  On Android (Termux), run:"
    echo "    mkdir -p ~/.ssh"
    echo "    echo '<paste key above>' >> ~/.ssh/authorized_keys"
    echo "    chmod 600 ~/.ssh/authorized_keys"
    read -p "  Press Enter once done..." _
  fi
fi

# ===== 5. LAUNCHD PLIST =====
echo ""
echo "── launchd agent ──"
sed "s|{{SCRIPT_DIR}}|$SCRIPT_DIR|g" \
  "$SCRIPT_DIR/com.user.photos-sync.plist.template" > "$PLIST_DEST"
# Disable by default — user enables with sync-enable
launchctl unload "$PLIST_DEST" 2>/dev/null || true
launchctl disable "gui/$(id -u)/${PLIST_LABEL}" 2>/dev/null || true
ok "plist installed (auto-sync is OFF — use sync-enable to turn it on)"

# ===== 6. SHELL ALIASES =====
echo ""
echo "── Shell aliases ──"
SHELL_RC="$HOME/.zshrc"
[ -n "$BASH_VERSION" ] && SHELL_RC="$HOME/.bashrc"

# Remove any previous block so we don't duplicate
if grep -q "# iphone-android-sync" "$SHELL_RC" 2>/dev/null; then
  # Delete the block between markers
  sed -i '' '/# iphone-android-sync -- begin/,/# iphone-android-sync -- end/d' "$SHELL_RC"
fi

cat >> "$SHELL_RC" <<RCEOF

# iphone-android-sync -- begin
_SYNC_PLIST="\$HOME/Library/LaunchAgents/${PLIST_LABEL}.plist"
_SYNC_DIR="${SCRIPT_DIR}"

alias sync-now="bash \"\$_SYNC_DIR/export-convert.sh\"; bash \"\$_SYNC_DIR/android-sync.sh\""
alias sync-import="bash \"\$_SYNC_DIR/export-convert.sh\""
alias sync-clear="truncate -s 0 \"${EXPORT_DIR}/.synced-manifest\" \"${EXPORT_DIR}/.android-synced-manifest\" && echo 'Manifests cleared.'"
alias sync-log="tail -30 /tmp/photos-sync.log"

sync-status() {
  if launchctl list 2>/dev/null | grep -q "${PLIST_LABEL}"; then
    echo "Auto-sync: ENABLED (runs every 2 min)"
  else
    echo "Auto-sync: DISABLED"
  fi
  echo "Last log entries:"
  tail -5 /tmp/photos-sync.log 2>/dev/null || echo "  (no log yet)"
}

sync-enable() {
  launchctl enable "gui/\$(id -u)/${PLIST_LABEL}"
  launchctl load "\$_SYNC_PLIST" 2>/dev/null
  echo "Auto-sync enabled (persists across reboots)."
}

sync-disable() {
  launchctl unload "\$_SYNC_PLIST" 2>/dev/null
  launchctl disable "gui/\$(id -u)/${PLIST_LABEL}"
  echo "Auto-sync disabled (persists across reboots)."
}
# iphone-android-sync -- end
RCEOF
ok "aliases added to $SHELL_RC"

# ===== 7. FULL DISK ACCESS REMINDER =====
echo ""
echo "── macOS Full Disk Access ──"
warn "If you plan to use auto-sync (sync-enable), grant Full Disk Access to /bin/bash:"
echo "     System Settings → Privacy & Security → Full Disk Access → add /bin/bash"
echo "  (Not needed for manual sync-now / sync-import)"

# ===== DONE =====
echo ""
echo "╔══════════════════════════════════════╗"
echo "║              All done!               ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "  Reload your shell:  source $SHELL_RC"
echo ""
echo "  Commands:"
echo "    sync-import   — pull from iPhone only"
echo "    sync-now      — pull from iPhone + push to Android"
echo "    sync-status   — show auto-sync state + recent log"
echo "    sync-enable   — start background auto-sync"
echo "    sync-disable  — stop background auto-sync"
echo "    sync-clear    — reset manifests (re-sync everything)"
echo "    sync-log      — tail the log"
echo ""
